#!/bin/bash
mkdir -p ~/Vídeos/Youtube/
echo "Cole o link do video aqui"
echo
echo "Depois aperte a tecla ENTER, para iniciar o Download"
echo " "
echo " " > ~/Documentos/youtubevideolinks.txt

#nano ~/Documentos/youtubevideolinks.txt
read links

echo $links >  ~/Documentos/youtubevideolinks.txt
terminal=`tty`

exec < ~/Documentos/youtubevideolinks.txt

while read -r line

do
    cd ~/Vídeos/Youtube/
    youtube-dl -f 18 "$line"
done
exec < "$terminal"

