#!/bin/bash
mkdir -p ~/Vídeos/Youtube/
echo " " > ~/Documentos/youtubevideolinks.txt

echo $1 >  ~/Documentos/youtubevideolinks.txt
terminal=`tty`

exec < ~/Documentos/youtubevideolinks.txt

while read -r line

do
    cd ~/Vídeos/Youtube/
    youtube-dl -f 18 "$line"
done
#exec < "$terminal"

